# Generated by Django 6.0.2 on 2026-03-08 12:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "blank": "Name cannot be empty.",
                            "null": "Name cannot be null.",
                            "required": "Name is required.",
                        },
                        help_text="Department name",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, message="Name must be at least 2 character long."
                            ),
                            django.core.validators.MaxLengthValidator(
                                200,
                                message="Name must be no more than 200 characters long.",
                            ),
                        ],
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        error_messages={
                            "does_not_exist": "Parent department with id {pk_value} does not exist.",
                            "invalid": "Incorrect type. Expected department ID value.",
                        },
                        help_text="Parent department ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="departments.departmentmodel",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        error_messages={
                            "blank": "Full name cannot be empty.",
                            "full_name": "Full name cannot be null.",
                            "required": "Full name is required.",
                        },
                        help_text="Employee full name",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2,
                                message="Full name must be at least 2 characters long.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                200,
                                message="Full name must be no more than 200 characters long.",
                            ),
                        ],
                        verbose_name="Full name",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        error_messages={
                            "blank": "Position cannot be empty.",
                            "null": "Position cannot be null.",
                            "required": "Position is required.",
                        },
                        help_text="Employee position",
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2,
                                message="Position must be at least 2 characters long.",
                            ),
                            django.core.validators.MaxLengthValidator(
                                200,
                                message="Position must be no more than 200 characters long.",
                            ),
                        ],
                        verbose_name="Position",
                    ),
                ),
                (
                    "hired_at",
                    models.DateField(blank=True, null=True, verbose_name="Hired date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        error_messages={
                            "does_not_exist": "Department with id {pk_value} does not exist.",
                            "required": "Department is required.",
                        },
                        help_text="Department where employee works",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="departments.departmentmodel",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["-created_at"],
            },
        ),
    ]
